<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php
            echo $this->getLayout()->createBlock('Magento\Catalog\Block\Navigation')->setTemplate('Magento_Catalog::navigation/left.phtml')->toHtml();
            ?>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="cat-name">Magento Extensions</h1>
                    <div class="category-description std">
                       <span class="text-short"> <p>Top Magento Extensions favoured by 50.000 customers worldwide. Pay one time and get free update &amp; 1-year free support. These extensions are mostly compatible with other extension providers and help you transform various areas like sales motivation, navigation, conversion rate, gift campaigns, stock
                               <span class="hidden-dot">...</span>
                               <span class="show-see-more collapse" id="show-see-more" style="display: none;">management &amp; more.</span></p></span>
                        <a data-toggle="collapse" data-target="#show-see-more" alt="View more" class="see-more-dec">View more</a>
                    </div>
                </div>
            </div>
            <div class="row">
            <?php if (!$_productCollection->count()): ?>
                <div class="message info empty">
                    <div><?php /* @escapeNotVerified */
                        echo __('We can\'t find products matching the selection.') ?></div>
                </div>
            <?php else: ?>
            <?php //echo $block->getToolbarHtml() ?>
            <?php //echo $block->getAdditionalHtml() ?>
            <?php
            if ($block->getMode() == 'grid') {
                $viewMode = 'grid';
                $image = 'category_page_grid';
                $showDescription = false;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            } else {
                $viewMode = 'list';
                $image = 'category_page_list';
                $showDescription = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
            }
            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
            ?>
                <div class="container-list-product products wrapper <?php /* @escapeNotVerified */
                echo $viewMode; ?> products-<?php /* @escapeNotVerified */
                echo $viewMode; ?>">

                    <?php $iterator = 1; ?>
                    <div class="list-product products list items product-items">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                        <?php foreach ($_productCollection as $_product): ?>
                            <?php /* @escapeNotVerified */
                            $prd_id = $_product->getId();
                            echo ($iterator++ == 1) ? '<div class="col-md-4 col-sm-6 id-'.$prd_id.' item">' : '</div><div class="col-md-4 col-sm-6 id-'.$prd_id.' item">' ?>
                            <div class="wrap-item-product">
                                <div class="wrap-to-click">
                                    <div class="top-product">
                                        <label class="short-desc">10X Faster Checkout</label>
                                        <a href="" class="product-image"><span class="iconic-icoExM1-06-WebPOS" style="background: none transparent;">
                <span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span><span class="path5"></span><span class="path6"></span><span class="path7"></span><span class="path8"></span>
                </span></a>
                                    </div>
                                    <div class="bottom-product">
                                        <h3 class="product-name"><a class="product-item-link"
                                                                    href="<?php /* @escapeNotVerified */
                                                                    echo $_product->getProductUrl() ?>">
                                                <?php /* @escapeNotVerified */
                                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                            </a></h3>
                                        <div class="price-reviews">
                                            <div class="row custom-flex">
                                                <div class="col-md-6 col-sm-6 col-xs-6  price-bottom">
                                                    <?php /* @escapeNotVerified */
                                                    echo $block->getProductPrice($_product) ?>
                                                </div>
                                                <div class="col-md-6 col-sm-6 col-xs-6  review-bottom">
                                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="actions">
                                        <button type="button" title="Add to Cart" class="button btn-cart"><span class="iconic-icoCart"></span></button>
                                    </div>
                                </div>

                            </div>
                            <?php echo ($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
                            <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $(document).ready(function () {
                                        var bg_color<?php echo $_product->getId()?> = $('.id-<?php echo $_product->getId()?> .top-product a > span').css('backgroundColor');
                                        $('.id-<?php echo $_product->getId()?> .top-product').css('backgroundColor', bg_color<?php echo $_product->getId()?>);
                                        $('.id-<?php echo $_product->getId()?> .top-product a > span').css('background', 'none transparent');
                                    });
                                });
                            </script>
                        <?php endforeach; ?>
                    </div>
                    </div>
                </div>
            <?php echo $block->getToolbarHtml() ?>
            <?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

                </script>
            <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
</div>