<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="container-footer">
    <div class="wrap-footer-magestore80">
        <a href="javascript:void(0)" id="home-back-to-top"><span class="iconic-icoBackTop"></span>Back to Top</a>
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-md-2">
                    <div class="footer-common footer-company">
                        <h3>COMPANY</h3>
                        <p><a href="//www.magestore.com/about-us.html/">About Us</a></p>
                        <p><a href="//www.magestore.com/our-customer-says.html/">Customer Reviews</a></p>
                        <p><a href="//www.magestore.com/press-room.html/">Press Room</a></p>
                        <p><a href="//www.magestore.com/partner-program.html/">Partner Program</a></p>
                        <p><a href="//www.magestore.com/affiliates/">Affiliate Program</a></p>
                        <!--p><a href="//www.magestore.com/our-partners.html/">Official Partners</a></p-->
                        <p><a href="//www.magestore.com/discount-program.html/">Promotional Programs</a></p>					</div>
                </div>
                <div class="col-sm-4 col-md-2">
                    <div class="footer-common footer-support">
                        <h3>Support</h3>
                        <p><a href="//www.magestore.com/faq/">FAQ</a></p>
                        <p><a href="//www.magestore.com/magento-tutorial">Magento Tutorial</a></p>
                        <p><a href="//www.magestore.com/magento-2-tutorial">Magento 2 Tutorial</a></p>
                        <p><a href="//www.magestore.com/community-helpdesk/" rel="canonical" target="_blank">Community Helpdesk</a></p>
                        <p><a href="//magestore.zendesk.com/" target="_blank">Ticket System</a></p>
                        <p><a href="mailto:support@magestore.com">Email Us</a></p>
                        <p><a href="//www.magestore.com/product-policy.html/">Product Policy</a></p>
                        <p><a href="http://www.magestore.com/terms-conditions.html/">Terms &amp; Conditions</a></p>
                        <p><a href="http://www.magestore.com/privacy-policy.html/">Privacy policy</a></p>
                        <p><a href="http://www.magestore.com/license-agreement.html/">License Agreement</a></p>					</div>
                </div>
                <div class="col-sm-4 col-md-2">
                    <div class="footer-common magestore-app">
                        <h3 class="title-app">MAGESTORE APP</h3>
                        <p><a class="link-app" href="https://itunes.apple.com/us/app/magestore-magento-marketing/id974418318?mt=8" target="_blank"><img src="http://www.magestore.com/skin/frontend/default/magestore8.0/images/magestore8.0/magestore-app.png" alt="Shop with Magestore App - Best Magento Markeing Extension Provider"></a></p>					</div>
                    <div class="footer-common shop-us">
                        <h3>SHOP WITH US</h3>
                        <p><a href="//www.magestore.com/magento-extensions.html">Magento Extensions</a></p>
                        <p><a href="http://www.magestore.com/affiliateplus/">Affiliate+ Extension</a></p>
                        <p><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Footer', 'eventAction': 'Click', 'eventLabel': 'SimiCart'});" href="https://www.simicart.com/?utm_source=Magestore%20New&amp;utm_medium=Click&amp;utm_content=Footer&amp;utm_campaign=Track%20Traffic%20Magestore" target="_blank">Magento® Shopping App</a></p>
                        <p><a href="//www.magestore.com/magento-services.html" rel="nofollow">Magento Services</a></p>
                        <p><a href="//www.magestore.com/free-magento-extensions.html" rel="nofollow">Free Stuff</a></p>
                        <p style="margin-bottom: 18px;"><a href="//www.magestore.com/timeline-update" rel="nofollow"><span>Product Updates</span></a></p>					</div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="footer-subscribe">
                        <div class="container-subscribes">
                            <form action="https://www.magestore.com/rewritecore/subscriber/new/" method="post" id="newsletter-validate-footer">
                                <h3>SUBSCRIBE TO GET $10</h3>
                                <div class="row">
                                    <div class="col-sm-8 col-xs-9">
                                        <div class="input-layout">
                                            <input id="newsletter-menu" class="input-text required-entry validate-email" title="Enter your email" type="text" name="email" required="">
                                            <span class="highlight"></span>
                                            <span class="bar"></span>
                                            <label for="newsletter-menu">Enter your email</label>
                                        </div>
                                    </div>
                                    <div class="col-sm-4 col-xs-3 wrap-actions">
                                        <button class="btn-subscribe" title="Subscribe" onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Newsletter', 'eventAction': 'Click', 'eventLabel': 'Subscribe Footer'});" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="footer-contact">
                        <h3>Contact</h3>
                        <p><label class="address">1750 Montgomery Street 1st Floor, San Francisco, CA 94111, United States.</label></p>
                        <p><strong>Call us: </strong><span class="number">+1-606-657-0768</span></p>
                        <div><div class="social-network">
                                <ul>
                                    <li class="first facebook">
                                        <div><a class="first facebook" title="Facebook" href="http://www.facebook.com/magestore" target="_blank"><span class="iconic-icoSocialFacebook">&nbsp; </span></a></div>
                                    </li>
                                    <li class="twitter">
                                        <div><a class="twitter" title="Twitter" href="https://twitter.com/magestore" target="_blank"><span class="iconic-icoSocialTwit">&nbsp; </span></a></div>
                                    </li>
                                    <li class="blog">
                                        <div><a class="blog" title="Magestore Blog" href="http://blog.magestore.com" target="_blank"><span class="iconic-icoSocialBlog">&nbsp; </span></a></div>
                                    </li>
                                    <li class="linkedin">
                                        <div><a class="linkedin" title="Linked In" href="https://www.linkedin.com/company/magestore" target="_blank"><span class="iconic-icoSocialIN">&nbsp; </span></a></div>
                                    </li>
                                    <li class="google">
                                        <div><a class="google" title="Google" href="https://plus.google.com/+magestore" target="_blank"><span class="iconic-icoSocialGoogle">&nbsp; </span></a></div>
                                    </li>
                                </ul>
                            </div></div>					</div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="footer-accept">
                        <div class="we-except ">
                            <h3 class="title-except">We Accept</h3>
                            <div class="clearer">&nbsp;</div>
                            <div class="wrap-except">
                                <div class="footer-payment"><img src="http://www.magestore.com/skin/frontend/default/magestore8.0/images/magestore8.0/footer-payment2.png" alt="Magestore Magento marketing extensions-Paypal"></div>
                                <div class="footer-security"><img src="http://www.magestore.com/skin/frontend/default/magestore8.0/images/magestore8.0/footer-security.png" alt="Magento Marketing Extenions - Magestore"></div>
                                <div class="footer-certified"><img src="http://www.magestore.com/media/wysiwyg/footer-certified.png" alt="Magento Certified Developer x5"><img src="http://www.magestore.com/media/wysiwyg/technology_partner_select.png" alt="Magento Select Technology Partner" style="
    width: 80px;
    margin-left: 30px;
"></div>
                            </div>
                        </div>					</div>
                </div>
            </div>
        </div>
    </div>
</div>
