<div class="parent-menu">
<div class="column">
<ul id="magestore-menu" class="nav navbar-nav">
    <li class="first dropdown menu-large toggle-items" data-url="magento-extensions.html"><span class="active-items active">Magento® extensions</span> <a class="active-items dropdown-toggle" title="Magento extensions" href="http://www.magestore.com/magento-extensions.html/" data-toggle="dropdown"><span>Magento® extensions</span></a> <strong class="caret"></strong>
        <div class="dropdown-menu megamenu row"><div class="container">
                <div class="row">
                    <ul>
                        <li class="col-sm-8">
                            <div class="row">
                                <div class="col-md-4 col-sm-6">
                                    <ul>
                                        <li class="menu-label"><label>Retailer Kit</label></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Inventory Management'});" href="http://www.magestore.com/magento-inventory-management-extension.html/"><span>Inventory Management </span></a><img style="width: 35px; height: 35px;" title="Magento inventory management extension" src="http://www.magestore.com/media/wysiwyg/animat-piechart-color.gif" alt="magento store manager extension"/></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'One Step Checkout'});" href="http://www.magestore.com/magento-one-step-checkout-extension.html/">One Step Checkout </a></span> <img title="Magento Affiliate Plus extension - Hot Updates" src="https://www.magestore.com/media/wysiwyg/label_update.png" alt="One Step Checkout Updates"/></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Gift Card'});" href="http://www.magestore.com/magento-gift-card-extension.html/">Gift Card</a> <img title="Magento Gift Card extension - Hot Updates" src="https://www.magestore.com/media/wysiwyg/label_update.png" alt="Gift Card Updates"/></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Web POS'});" href="http://www.magestore.com/magento-pos-integration-extension.html/"><span>Web POS</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Reward Points Plus'});" href="http://www.magestore.com/rewardpoints/">Reward Points Plus&nbsp;</a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Affiliate Plus'});" href="http://www.magestore.com/affiliateplus">Affiliate Plus</a> <img title="Magento Affiliate Plus extension - Hot Updates" src="https://www.magestore.com/media/wysiwyg/label_update.png" alt="Affiliate Updates"/></li>

                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Store Credit 2'});" href="http://www.magestore.com/magento-store-credit-extension.html/"><span>Store Credit</span></a></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Store Locator'});" href="http://www.magestore.com/magento-store-locator-extension.html/">Store Locator</a></span></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Store Pickup'});" href="http://www.magestore.com/magento-store-pickup-extension.html/">Store Pickup</a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'PDF Invoice Plus'});" href="http://www.magestore.com/magento-pdf-invoice-extension.html/"><span>PDF Invoice Plus</span></a></li>
                                    </ul>
                                </div>
                                <div class="col-md-4 col-sm-6">
                                    <ul class="first">
                                        <li class="menu-label"><label> Navigation </label></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Mega Menu 2'});" href="http://www.magestore.com/magento-mega-menu-extension.html/">Mega Menu</a> <!--img title="Magento Mega Menu extension - Hot Updates" src="http://www.magestore.com/media/wysiwyg/label_update.png" alt="Mega Menu Updates" /--></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Shop by Brand 2'});" href="http://www.magestore.com/magento-shop-by-brand-extension.html/"><span>Shop by Brand</span></a></li>
                                    </ul>
                                    <ul style="margin-bottom: 20px;">
                                        <li class="menu-label"><label> Sales Motivation </label></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Membership', 'eventAction': 'Click', 'eventLabel': 'Membership'});" href="http://www.magestore.com/magento-membership-extension.html/">Membership</a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Gift Wrap'});" href="http://www.magestore.com/magento-gift-wrap-extension.html/"><span>Gift Wrap</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Auction'});" href="http://www.magestore.com/magento-auction-extension.html/"><span>Auction</span></a></li>
                                    </ul>
                                    <ul>
                                        <li class="menu-label"><label> User Experience </label></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Social Login'});" href="http://www.magestore.com/magento-social-login-extension.html/">Social Login </a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'FAQ'});" href="http://www.magestore.com/magento-faq-extension.html/"><span>FAQ </span></a></li>
                                    </ul>
                                </div>
                                <div class="col-md-4 col-sm-12">
                                    <ul style="margin-bottom: 20px;">
                                        <li class="menu-label"><label> Best Sellers </label></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'One Step Checkout-Best'});" href="http://www.magestore.com/magento-one-step-checkout-extension.html/">One Step Checkout </a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Gift Card-Best'});" href="http://www.magestore.com/magento-gift-card-extension.html/">Gift Card</a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Inventory Management-Best'});" href="http://www.magestore.com/magento-inventory-management-extension.html/"><span>Inventory Management </span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Web POS-Best'});" href="http://www.magestore.com/magento-pos-integration-extension.html/"><span>Web POS</span></a></li>
                                    </ul>
                                    <ul style="margin-bottom: 20px;">
                                        <li class="menu-label"><label> Mobile </label></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'SimiCart'});" href="https://www.simicart.com/?utm_source=Magestore%20New&amp;utm_medium=Click&amp;utm_content=Mega%20Menu&amp;utm_campaign=Track%20Traffic%20Magestore" target="_blank"><span>Magento® Shopping App</span></a></li>
                                </div>
                            </div>
                        </li>
                        <li class="col-sm-4  banner-menu">
                            <div id="update-menu2">
                                <ul>
                                    <li class="last">
                                        <h4>Well-prepared Sales Season with Retailer Kit</h4>
                                        <a title="banner_menu" href="http://www.magestore.com/retailer-kit.html/?utm_source=Magestore&amp;utm_medium=mega-menu&amp;utm_campaign=Retailer-Kit-Accumulate#promotion" target="_blank"> <img src="http://www.magestore.com/media/wysiwyg/BannerRetailerkit-08.jpg" alt="Retailer Kit Sales Season" width="354" height="197"/></a>
                                        <p>&nbsp;</p>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div></div>
    </li>
    <li class="dropdown menu-large toggle-items" data-url="magento-2-extensions.html"><span class="active-items active">Magento® 2 extensions</span> <a class="active-items dropdown-toggle" title="Magento extensions" href="http://www.magestore.com/magento-2-extensions.html/" data-toggle="dropdown"><span>Magento® 2 extensions</span></a> <strong class="caret"></strong>
        <div class="dropdown-menu megamenu row"><div class="container">
                <div class="row">
                    <ul>
                        <li class="col-sm-4 banner-menu-left">
                            <div id="update-menu3">
                                <ul>
                                    <li class="last">
                                        <div class="subscribe-box">
                                            <h3 class="title">DON'T BE LEFT BEHIND!</h3>
                                            <div class="container-content">
                                                <div class="form-subscribe-header"><label class="newsletter">A bunch of really cool stuff about Magento &amp; M2 extensions will come into your inbox weekly. Get 10 points ($10) in reward.</label></div>
                                                <div class="container-leftmenu">
                                                    <form action="https://www.magestore.com/rewritecore/subscriber/new/" method="post" id="newsletter-validate-magento2">
                                                        <div class="row">
                                                            <div class="col-md-8">
                                                                <div class="input-layout">
                                                                    <input id="newsletter-menu" class="input-text required-entry validate-email" title="Sign up for our newsletter" type="text" name="email" required="">
                                                                    <span class="highlight"></span>
                                                                    <span class="bar"></span>
                                                                    <label for="newsletter-menu">Enter your email</label>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-4">
                                                                <button class="btn-subscribe" title="Subscribe" onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Newsletter', 'eventAction': 'Click', 'eventLabel': 'Place a seat'});" type="submit">Submit</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                                <script type="text/javascript">

                                                    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-magento2');

                                                </script></div>
                                        </div>
                                        <a href="//www.magestore.com/magento-promotion-extensions.html/?utm_source=Magestore&amp;utm_medium=mega-menu2&amp;utm_campaign=Weekly-Deal" target="_blank"> <img src="http://www.magestore.com/media/wysiwyg/weekly_Mega_Menu.jpg" alt="Weekly Deal 2016" width="354" height="197"/></a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="col-sm-8  list-link-menu">
                            <div class="row">
                                <div class="col-md-4 col-sm-6">
                                    <ul>
                                        <li class="menu-label"><label> Retailer Kit</label></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'IM'});" href="http://www.magestore.com/magento-2-inventory-management-extension.html/">Inventory Management</a></span><span style="color: red;"> (NEW)</span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Web POS'});" href="http://www.magestore.com/magento-2-pos-extension.html/">Web POS</a> <img title="Magento Affiliate Plus extension - Hot Updates" src="https://www.magestore.com/media/wysiwyg/label_update.png" alt="Web POS 2 Updates"/></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'One Step Checkout'});" href="http://www.magestore.com/magento-2-one-step-checkout-extension.html/">One Step Checkout</a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Gift Card'});" href="http://www.magestore.com/magento-2-gift-card-extension.html/">Gift Card </a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Affiliate Plus'});" href="http://www.magestore.com/magento-2-affiliateplus.html">Affiliate Plus </a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Reward Points Plus'});" href="http://www.magestore.com/magento-2-reward-points.html/"><span>Reward Points Plus</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Store Credit 2'});" href="http://www.magestore.com/magento-2-store-credit-extension.html/"><span>Store Credit</span></a></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Store Locator'});" href="http://www.magestore.com/magento-2-store-locator-extension.html/">Store Locator</a></span></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Store Pickup'});" href="http://www.magestore.com/magento-2-store-pickup-extension.html/">Store Pickup</a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'PDF Invoice Plus'});" href="http://www.magestore.com/magento-2-pdf-invoice-extension.html/"><span>PDF Invoice Plus</span></a></li>
                                    </ul>
                                </div>
                                <div class="col-md-4 col-sm-6">
                                    <ul class="first">
                                        <li class="menu-label"><label> Navigation </label></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Mega Menu 2'});" href="http://www.magestore.com/magento-2-mega-menu-extension.html/">Mega Menu</a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Shop by Brand 2'});" href="http://www.magestore.com/magento-2-shop-by-brand-extension.html/"><span>Shop by Brand</span></a></li>
                                    </ul>
                                    <ul>
                                        <li class="menu-label"><label> User Experience </label></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Social Login'});" href="http://www.magestore.com/magento-2-social-login-extension.html/">Social Login </a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'FAQ'});" href="http://www.magestore.com/magento-2-faq-extension.html/"><span>FAQ </span></a></li>
                                    </ul>
                                </div>
                                <div class="col-md-4 col-sm-12">
                                    <ul class="first">
                                        <li class="menu-label"><label> Order Success </label></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'IMsuccess'});" href="//www.magestore.com/magento-2-inventory-management-extension.html/"><span>Inventory Management</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Barcode'});" href="//www.magestore.com/inventory/magento-2-barcode-management-extension.html"><span>Barcode Management</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Purchase'});" href="http://www.magestore.com/magento-2-purchase-management-extension.html"><span>Purchase Management</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Order Fulfillment'});" href="//www.magestore.com/inventory/magento-2-order-fulfillment-extension.html"><span>Order Fulfillment</span></a><span style="color: red;"> (NEW)</span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Dropship'});" href="///www.magestore.com/inventory/magento-2-dropship-extension.html"><span>Dropship</span></a><span style="color: red;"> (NEW)</span></li>
                                    </ul>
                                    <ul>
                                        <li class="menu-label"><label> Sales Motivation </label></li>
                                        <li class="menu-links"><span><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Membership', 'eventAction': 'Click', 'eventLabel': 'Membership'});" href="http://www.magestore.com/magento-2-membership-extension.html/">Membership</a></span></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Gift Wrap'});" href="http://www.magestore.com/magento-2-gift-wrap-extension.html/"><span>Gift Wrap</span></a></li>
                                        <li class="menu-links"><a onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Magestore\'s Mega Menu', 'eventAction': 'Click', 'eventLabel': 'Auction'});" href="http://www.magestore.com/magento-2-auction-extension.html/"><span>Auction</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div></div>
    </li>
    <li class="link-menu"><a title="Magento Retail Plus Collection" href="http://www.magestore.com/retailer-kit.html/">Retailer Kit</a></li>
    <li class="link-menu"><a title="Magento Affiliate Plus extension" href="http://www.magestore.com/affiliateplus"><span>Affiliate+</span></a></li>
    <li class="link-menu"><a title="Magento Reward Points extension" href="http://www.magestore.com/rewardpoints"><span>Reward Points</span></a></li>
    <li class="link-menu">
        <div class="dropdown">
            <div class="dropdown-toggle custom-toggle" data-toggle="dropdown">Inventory<span class="caret">&nbsp;</span></div>
            <ul class="dropdown-menu dropdown-menu-custom">
                <li class="custom-li"><a title="Magento 1 Inventory" href="//www.magestore.com/inventory"><span>Magento 1 Inventory</span></a></li>
                <li class="divider"></li>
                <li class="custom-li"><a title="Magento 2 Inventory" href="//www.magestore.com/inventory/magento-2.html/"><span>Magento 2 Inventory</span></a></li>
            </ul>
        </div>
    </li>
    <li class="link-menu">
        <div class="dropdown">
            <div class="dropdown-toggle custom-toggle" data-toggle="dropdown">Magento® POS<span class="caret">&nbsp;</span></div>
            <ul class="dropdown-menu dropdown-menu-custom">
                <li class="custom-li"><a title="Magento® POS" href="http://www.magestore.com/magento-pos-integration-extension.html/"><span>Magento POS</span></a></li>
                <li class="divider"></li>
                <li class="custom-li"><a title="Magento 2® POS" href="http://www.magestore.com/magento-2-pos-extension.html/"><span>Magento 2 POS</span></a></li>
            </ul>
        </div>
    </li>
    <li class="last link-menu"><a title="Magento Services" href="http://www.magestore.com/magento-services.html"><span>Magento® Service</span></a></li>
</ul>
</div>
</div>